--- 
analyze_grasp_topic: analyze_grasp_action
move_group_name: arm
grasp_approach_tran_frame: approach_tran
reachability_analyzer/planner_config_name: "[PRMkConfigDefault]"
end_effector_name: gripper
reachability_analyzer/allowed_planning_time: 15

pre_grasp_goal_point.effort: [50,50]
pre_grasp_goal_point.positions: [0.04, 0.04]
pre_grasp_goal_point.time_from_start.secs: 2

pre_grasp_joint_names:  ['l_gripper_finger_joint', 'r_gripper_finger_joint']

grasp_goal_point.effort: [50,50]
grasp_goal_point.positions: [0.04, 0.04]
grasp_goal_point.time_from_start.secs: 2

moveit_grasp.grasp_posture.joint_names: ['l_gripper_finger_joint', 'r_gripper_finger_joint']

moveit_grasp.pre_grasp_approach.min_distance: 0.05
moveit_grasp.pre_grasp_approach.desired_distance: 0.1
moveit_grasp.pre_grasp_approach.direction.header.frame_id: "/wrist_roll_link"

moveit_grasp.post_grasp_retreat.min_distance: 0.05
moveit_grasp.post_grasp_retreat.desired_distance: 0.1
moveit_grasp.post_grasp_retreat.direction.header.frame_id: "/base_link"
moveit_grasp.post_grasp_retreat.direction.vector.x: 0
moveit_grasp.post_grasp_retreat.direction.vector.y: 0
moveit_grasp.post_grasp_retreat.direction.vector.z: 1

moveit_grasp.max_contact_force: -1
